### ISSUE TITLE
(Not a issue) How to handle if HomeScreen was further meant to have Bottom Tabs

### ISSUE THREAD

**Issue by kran-rana87** [raamcosta/navigation-tests#4]
Would you recommend having a second Nav Host for handling the tabs in the Home Screen?

**Comment by raamcosta** [comment]
Hi 👋 

Im sorry I missed the notification when the issue was created.

Usually the recommendation is to hide the bottom bar or show it based on a condition in the Scaffold. Multiple NavHosts is something we want to avoid if possible.
